name: app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/add.png
    - assets/icons/android.png
    - assets/icons/apple.png
    - assets/icons/award.png
    - assets/icons/budget.png
    - assets/icons/bulb.png
    - assets/icons/check.png
    - assets/icons/clock.png
    - assets/icons/close.png
    - assets/icons/doc.png
    - assets/icons/facebook.png
    - assets/icons/group.png
    - assets/icons/instagram.png
    - assets/icons/linkedin.png
    - assets/icons/logo.png
    - assets/icons/mail.png
    - assets/icons/message.png
    - assets/icons/phone.png
    - assets/icons/phone_2.png
    - assets/icons/pin.png
    - assets/icons/plane.png
    - assets/icons/profile.png
    - assets/icons/rocket.png
    - assets/icons/twitter.png
    - assets/icons/user.png
    - assets/icons/wallet.png
    - assets/ilustrations/ilustration_1.png
    - assets/ilustrations/ilustration_2.png
    - assets/ilustrations/ilustration_3.png
    - assets/ilustrations/ilustration_4.png
    - assets/ilustrations/ilustration_5.png
    - assets/ilustrations/ilustration_6.png
    - assets/ilustrations/ilustration_7.png
    - assets/ilustrations/ilustration_8.png
    - assets/ilustrations/ilustration_9.png
    - assets/ilustrations/ilustration_10.png
    - assets/ilustrations/home_banner.png
    - assets/images/result_1643960.jpeg
    - assets/images/result_1643962.jpeg
    - assets/images/result_1644065.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700